### ISSUE TITLE
App failing to load

### ISSUE THREAD

**Issue by MikeJohnPage** [Public-Health-Scotland/scotpho-profiles-tool#48]
The app is failing to load today. It gets stuck on the default "Please Wait" loading screen from shinyapps.io, suggesting shinyapps.io is failing to boot up an instance.

This has been checked across different browsers (Safari/Firefox/Chrome) and machines.

**Comment by jvillacampa** [comment]
@MikeJohnPage Thanks for letting us know. We have restarted the shinyapps.io side and now it seems to be working fine. Please let us know if the issue persists.

**Comment by MikeJohnPage** [comment]
All working now - thanks for fixing 👍
